apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image:   # Sets Image
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: '1'
          limits:
            cpu: '1'
            memory: 1Gi
        ports:
        - containerPort: 5432
        - containerPort: 8000      # Exposes container port
        envFrom:
        - configMapRef:
            name: postgres-config
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-claim
